### PR TITLE
Change course info colour and margins. Fixes #358.

### LINKED ISSUE #358: Course info change formatting and color
issue05

- Change blue background behind course title to #3F51B5 
- Description shouldn't be bold but probably medium. Correct me if I'm wrong
- Not enough padding on top and needs little more (refer to dining/directory) on the left

### PR DESCRIPTION
**Pull request by lilyidi**

### CODE REVIEW

File: PennMobile/src/main/java/com/pennapps/labs/pennmobile/CourseFragment.java [hunk 1]
```diff
@@ -25,6 +25,7 @@
 import com.pennapps.labs.pennmobile.classes.MapCallbacks;
 import com.pennapps.labs.pennmobile.classes.Review;
 
+
```
Comment (jasontsh) [inline PennMobile/src/main/java/com/pennapps/labs/pennmobile/CourseFragment.java]: Delete this line.

File: PennMobile/src/main/res/layout/fragment_course.xml [hunk 2]
```diff
@@ -132,15 +132,15 @@
                 android:layout_width="match_parent"
                 android:layout_height="wrap_content"
                 android:orientation="vertical"
-                android:layout_marginLeft="15dp"
-                android:layout_marginRight="15dp"
+                android:layout_marginLeft="@dimen/activity_horizontal_margin"
+                android:layout_marginRight="@dimen/activity_horizontal_margin"
+                android:layout_marginTop="@dimen/activity_vertical_margin"
```
Comment (jasontsh) [inline PennMobile/src/main/res/layout/fragment_course.xml]: These should be padding, not margin.

**Comment by jasontsh** [comment]
LGTM
